sudo: required
services:
  - docker
git:
  submodules: false
script:
  - git submodule update --init || true because landing-page-hugo has infinite recursion of submodules
  - docker build -t imagemagick -f Dockerfile.imagemagick .
  - ./createbook.sh
  - ./build.sh
after_success:
  - echo $DEPLOY_KEY | base64 -d > id_ed25519
  - chmod 600 id_ed25519
  - ssh-add id_ed25519
  - ./deploy.sh
