sudo: required
services:
  - docker
script:
  - git submodule update --init --recursive
  - docker build -t imagemagick -f Dockerfile.imagemagick
  - ./createbook.sh
  - ./build.sh
after_success:
  - ./deploy.sh
