# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://100pour100massif.fr
title: 100% Massif
email: elie.lombard@free.fr
author: Elie Lombard
description: > # "Write an awesome description for your new site here. 
  Mobilier et agencement en Chartreuse"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

mainlinks:
  - id: index
    title: Présentation
  - id: concept
    title: Concept
  - id: realisations
    title: Réalisations

social:
  - title: email
    icon: envelope
    url: mailto:nospam@domain
  # - title: twitter
  #   url: https://twitter.com/SBootstrap
  # - title: github
  #   url: https://github.com/IronSummitMedia/startbootstrap
  # - title: linkedin
  #   url: 
