disablePathToLower: true
languageCode: fr-fr
title: 100% Massif
publishDir: publish
theme: landing-page-hugo
taxonomies:
  categorie: categories
params:
  custom_css:
    - /css/style.css
  custom_js:
    - /js/style.js
  social:
    - title: "email"
      icon: "envelope-o"
      url: "mailto:contact@100pour100massif.fr"
    - title: "téléphone : 06 50 99 99 41"
      icon: "phone"
      url: "tel:+33-6-50-99-99-41"
...