baseURL: http://100pour100massif.fr
disablePathToLower: true
languageCode: fr-fr
title: 100% Massif
publishDir: publish
theme: landing-page-hugo
params:
  custom_css:
    - /css/style.css
  custom_js:
    - /js/style.js
  social:
    - title: "email"
      icon: "envelope-o"
      url: "mailto:elie.lombard+web@free.fr"
...