backend:
  name: git-gateway
  #name: test-repo
  branch: netlify # Branch to update (optional; defaults to master)

# Editorial workflow
publish_mode: editorial_workflow

media_folder: "assets/media"
public_folder: "/media"

collections:
  - name: "about"  # in routes
    label: "Pages" # in UI
    folder: "content"
    slug: "{{slug}}"
    fields: # front matter
      - name:   title
        label:  Titre
        widget: string
      - name:   date
        label:  Date
        widget: datetime
      - name:   body
        label:  Contenu
        widget: markdown
  - name: "presentation"  # in routes
    label: "Présentation" # in UI
    folder: "content/presentation"
    create: true
    slug: "{{slug}}"
    fields: # front matter
      - name:   title
        label:  Titre
        widget: string
      - name:   date
        label:  Date
        widget: datetime
      - name:   weight
        label:  Ordre
        widget: number
      - name:   img
        label:  Image
        widget: image
      - name:   body
        label:  contenu
        widget: markdown
  - name:   gallerie
    label:  Gallerie
    folder: content/gallerie
    create: true
    fields:
      - name:   title
        label:  Titre
        widget: string
      - name:   date
        label:  Date
        widget: datetime
      - name:     prestations
        label:    Prestations
        widget:   list
        required: false
        field:
          name:   prestation
          label:  Prestation
          widget: string
      - name:    weight
        label:   Ordre
        widget:  number
        default: 0
      - name:     images
        label:    Images
        widget:   list
        required: false
        field:
          name:   image
          label:  Image
          widget: image
          media_library:
            config:
              multiple: true
      - name:     body
        label:    contenu
        widget:   markdown
        required: false

