backend:
  name: git-gateway
  #name: test-repo
  branch: netlify # Branch to update (optional; defaults to master)

local_backend: true

# Editorial workflow (disabled for simplicity)
# publish_mode: editorial_workflow

media_folder: "/assets/media"
public_folder: "/media"

collections:
  - name: "about"  # in routes
    label: "Pages" # in UI
    folder: "content"
    slug: "{{slug}}"
    fields: # front matter
      - name:   title
        label:  Titre
        widget: string
      - name:   date
        label:  Date
        widget: datetime
      - name:   body
        label:  Contenu
        widget: markdown
        required: false
  - name: "presentation"  # in routes
    label: "Philosophie" # in UI
    folder: "content/presentation"
    create: true
    slug: "{{slug}}"
    fields: # front matter
      - name:   title
        label:  Titre
        widget: string
      - name:   date
        label:  Date
        widget: datetime
      - name:   weight
        label:  Ordre
        widget: number
      - name:   img
        label:  Image
        widget: image
      - name:   body
        label:  contenu
        widget: markdown
        required: false
  - name: "categories"  # in routes
    label: "Catégories" # in UI
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    nested:
      depth: 2
      summary: '{{title}}'
    fields: # front matter
      - name:   title
        label:  Titre
        widget: string
      - name:   date
        label:  Date
        widget: datetime
      - name:   weight
        label:  Ordre
        widget: number
      - name:     image
        label:    Image
        widget:   image
        required: false
      - name:   body
        label:  contenu
        widget: markdown
        required: false
  - name:   realisations
    label:  Réalisations
    folder: content/realisations
    create: true
    fields:
      - name:   title
        label:  Titre
        widget: string
      - name:   date
        label:  Date
        widget: datetime
      - name:     categories
        label:    Catégories
        widget:   list
        required: false
        default:  ['autre']
        field:
          name:      categorie
          label:     Catégorie
          widget:    select
          collapsed: false
          options:
            - cuisines
            - salles-de-bain
            - vitrines-buffets-vaisseliers
            - tables
            - portes
            - escaliers
            - dressings
            - lits
            - divers
      - name:    weight
        label:   Ordre
        widget:  number
        default: 0
      - name:     images
        label:    Images
        widget:   list
        required: false
        field:
          name:      image
          label:     Image
          widget:    image
          collapsed: false
          media_library:
            config:
              multiple: true
      - name:     body
        label:    contenu
        widget:   markdown
        required: false

